export enum ErrorCode {
    NOT_FOUND = "NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    AUTHENTICATION = "AUTHENTICATION_ERROR",
    VALIDATION = "VALIDATION_FAILED",
    DATABASE = "DB_ERROR",
    SERVER = "INTERNAL_ERROR",
    ALREADY_EXISTS = "ALREADY_EXISTS"
}